<a href="https://colab.research.google.com/github/mouhamedlaminembaye/Accord-de-credit-bancaire/blob/main/Introduction_ANN_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction Artificial Neural Network

### Import libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.20.0'

## Part 1 : Data Preprocessing

#### Import the dataset

In [4]:
dataset = pd.read_excel('/content/sample_data/Folds5x2_pp.xlsx')
dataset.head()

,AT,V,AP,RH,PE
0,14.96,41.76,1024.07,73.17,463.26
1,25.18,62.96,1020.04,59.08,444.37
2,5.11,39.40,1012.16,92.14,488.56
3,20.86,57.32,1010.24,76.64,446.48
4,10.82,37.50,1009.23,96.62,473.90


In [5]:
X = dataset.iloc[:, :-1].values
y =dataset.iloc[:, -1].values

In [7]:
X, y

(array([[  14.96,   41.76, 1024.07,   73.17],
        [  25.18,   62.96, 1020.04,   59.08],
        [   5.11,   39.4 , 1012.16,   92.14],
        ...,
        [  31.32,   74.33, 1012.92,   36.48],
        [  24.48,   69.45, 1013.86,   62.39],
        [  21.6 ,   62.52, 1017.23,   67.87]]),
 array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28]))

#### Split the dataset into training and test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Part 2 : Building the ANN

#### Initialize the ANN

In [17]:
# Initialize the ann as  sequence of layers
ann = tf.keras.models.Sequential()

#### Adding the input layer and the hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the second hidden layers

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units=1))

## PArt 3 : Train the ANN

#### Compile the AN

In [21]:
ann.compile(optimizer='adam', loss='mean_squared_error')

#### Train the model

In [23]:
ann.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 2784.7063 - val_loss: 401.2602
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 367.0377 - val_loss: 339.9893
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 301.4710 - val_loss: 270.8871
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 233.8211 - val_loss: 204.4273
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 170.6231 - val_loss: 145.9252
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 118.6745 - val_loss: 98.8842
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 81.2015 - val_loss: 67.8108
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 57.7543 - val_loss: 50.4675
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 45.9010 - val_loss: 42.2476
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 40.8837 - val_loss: 39.7535
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 38.9261 - val_loss: 38.9496
Epoch 1

#### Predicting the result of the tesrt set

In [28]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[429.06 431.23]
 [460.   460.01]
 [463.46 461.14]
 ...
 [470.72 473.26]
 [437.59 438.  ]
 [456.76 463.28]]
